export const cardsPlugin = [
  "1C-Bitrix",
  "Drupal 8/ Ubercart/ Commrce",
  "MODX miniShop2",
  "WooCommerce. Also supports WooCommerceTM Subscriptions",
  "WordPress",
  "HikaShop",
  "HostCMS",
  "Sitebill",
  "PrestaShop 1.5.x/ 1.6.x/ 1.7.x",
  "Shop-Script 7/8. Also works with Webasyst CRM",
  "VirtueMart / VirtueMart 1.1.9",
  "OpenCart 1.5 /2.0 /2.1 /2.2 /3.0",
  "JoomShopping",
  "Magento/ Magento 2",
  "WHMCS",
  "Shopkeeper3",
  "CS-Cart 4.2.x/ 4.5.x/ 4.6.x/ 4.7.x",
  "ReadyScript",
  "Simpla",
  "J2Store",
  "DIAFAN.CMS",
  "HopeBilling",
  "VamShop",
  "Billmanager",
  "WP Charitable",
  "Easy Digital Downloads"
];
